<?php
return array(
  array(
    'name' => 'Adam Warski',
    'twitter' => 'adamwarski',
    'blog' => 'http://www.warski.org/blog/',
    'username' => 'warski',
  ),
  array(
    'name' => 'Aleksandra Puchta',
    'twitter' => 'PuchtaOla',
    'blog' => NULL,
    'username' => 'puchta',
  ),
  array(
    'name' => 'Damian Nowak',
    'twitter' => 'nwkr',
    'blog' => 'http://www.nowaker.net/',
    'username' => 'nowak',
  ),
  array(
    'name' => 'Jacek Kunicki',
    'twitter' => 'rucek',
    'blog' => 'http://blog.kunicki.org',
    'username' => 'kunicki',
  ),
  array(
    'name' => 'Jan Zborowski',
    'twitter' => NULL,
    'blog' => NULL,
    'username' => 'zborowski',
  ),
  array(
    'name' => 'Jarosław Kijanowski',
    'twitter' => 'jkijanowski',
    'blog' => 'http://kijanowski.blogspot.com/',
    'username' => 'kijanowski',
  ),
  array(
    'name' => 'Kinga Pukianiec',
    'twitter' => NULL,
    'blog' => NULL,
    'username' => 'pukianiec',
  ),
  array(
    'name' => 'Krzysztof Ciesielski',
    'twitter' => 'kpciesielski',
    'blog' => 'http://abstractionextraction.wordpress.com/',
    'username' => 'ciesielski',
  ),
  array(
    'name' => 'Krzysztof Grajek',
    'twitter' => 'grajo',
    'blog' => 'http://www.softwarepassion.com/',
    'username' => 'grajek',
  ),
  array(
    'name' => 'Łukasz Lenart',
    'twitter' => 'lukaszlenart',
    'blog' => 'http://dailylog.lenart.org.pl/',
    'username' => 'lenart',
  ),
  array(
    'name' => 'Łukasz Żuchowski',
    'twitter' => 'zuchos',
    'blog' => 'http://blog.zuchos.com/',
    'username' => 'zuchowski',
  ),
  array(
    'name' => 'Maciej Biłas',
    'twitter' => 'maciejb',
    'blog' => 'http://maciej.inszy.org/',
    'username' => 'bilas',
  ),
  array(
    'name' => 'Maciej Hnydka',
    'twitter' => NULL,
    'blog' => NULL,
    'username' => 'hnydka',
  ),
  array(
    'name' => 'Małgorzata Wojciechowska',
    'twitter' => NULL,
    'blog' => NULL,
    'username' => 'wojciechowska',
  ),
  array(
    'name' => 'Michał Matłoka',
    'twitter' => 'mmatloka',
    'blog' => NULL,
    'username' => 'no-image',
  ),
  array(
    'name' => 'Michał Ostruszka',
    'twitter' => 'mostruszka',
    'blog' => 'http://michalostruszka.pl',
    'username' => 'ostruszka',
  ),
  array(
    'name' => 'Paweł Stawicki',
    'twitter' => 'pawelstawicki',
    'blog' => 'http://pawelstawicki.blogspot.com/',
    'username' => 'stawicki',
  ),
  array(
    'name' => 'Paweł Wrzeszcz',
    'twitter' => 'pawelwrzeszcz',
    'blog' => 'http://pawel.wrzesz.cz/',
    'username' => 'wrzeszcz',
  ),
  array(
    'name' => 'Piotr Buda',
    'twitter' => 'piotrbuda',
    'blog' => 'http://piotrbuda.eu/',
    'username' => 'buda',
  ),
  array(
    'name' => 'Tomasz Dziurko',
    'twitter' => 'TomaszDziurko',
    'blog' => 'http://tomaszdziurko.pl/',
    'username' => 'dziurko',
  ),
  array(
    'name' => 'Tomasz Szymański',
    'twitter' => 'szimano',
    'blog' => 'http://szimano.org/',
    'username' => 'szymanski',
  ),
);
